apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: products-service-data
  namespace: microservices
  labels:
    app: products-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
