apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: microservices
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users
          image: service1:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: users-service-config
            - secretRef:
                name: users-service-secrets
